[package]
name = "bevy_baduk"
version = "0.1.0"
authors = ["mcparland"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.1.3"
snafu = "0.6.8"
colored = "2.0.0"